from pathlib import Path
import json, html, hashlib
root=Path(__file__).resolve().parent
items=[
('screenshots/01-macbook-notch.png','At home on your MacBook','Devices','Native notch timer in an illustrative MacBook frame.'),
('screenshots/02-external-monitor.png','Room to do your best work','Devices','Floating timer and focus history on an illustrative external display.'),
('screenshots/03-start-a-session.png','Name the work','Workflow','A clear intention, a project, and 25 minutes.'),
('screenshots/04-stay-focused.png','Stay with the good work','Workflow','The native running timer and compact session controls.'),
('screenshots/05-queue-a-thought.png','A thought for later','Workflow','Capture the next task while your current timer keeps running.'),
('screenshots/06-next-task-queued.png','Your next step is waiting','Workflow','The next task stays in To do until you are ready.'),
('screenshots/07-task-completed.png','One thing done','Workflow','The current task is complete. The next one is ready to start.'),
('screenshots/08-next-task-running.png','Keep the momentum','Workflow','The enqueued launch announcement now has your attention.'),
('screenshots/09-report-week.png','Your week, made visible','Reports','Seven days of focused work across three projects.'),
('screenshots/10-report-day.png','Give today its due','Reports','A daily view of your focused time and completed sessions.'),
('screenshots/11-report-project.png','Follow a project’s progress','Reports','The seven-day report, filtered to Studio.'),
('screenshots/12-project-timeline.png','See the work behind the hours','Reports','Project totals lead into the individual session history.'),
('native/report-day.png','Daily report · native detail','Reports','A 2× native capture of today’s totals, projects, and session list.'),
('native/report-week.png','Weekly report · native detail','Reports','A 2× native capture with daily bars and project breakdowns.'),
('native/report-project.png','Project report · native detail','Reports','A 2× native capture of the Studio project report.'),
]
manifest=[]
cards=[]
for path,title,category,description in items:
    manifest.append(dict(path=path,title=title,category=category,description=description,sha256=hashlib.sha256((root/path).read_bytes()).hexdigest()))
    cards.append(f'<article data-category="{category}"><a class="preview" href="{path}" target="_blank"><img src="{path}" alt="{html.escape(description)}" loading="lazy"></a><div class="info"><small>{category}</small><h3>{html.escape(title)}</h3><p>{html.escape(description)}</p><a class="download" href="{path}" download>Download PNG ↗</a></div></article>')
(root/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
chapters=json.loads((root/'video/chapters.json').read_text())
links=''.join(f'<button class="chapter" data-time="{c["start"]}"><span>{int(c["start"])//60}:{int(c["start"])%60:02}</span>{html.escape(c["title"])}</button>' for c in chapters)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blocks — Showcase library</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080f12;color:#e8f0ed;font:16px -apple-system,BlinkMacSystemFont,system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:64px 40px 80px}header{display:flex;justify-content:space-between;align-items:center;color:#a2d9c7}header a{color:inherit}h1{font-size:clamp(46px,6vw,88px);line-height:1.03;letter-spacing:-.055em;margin:75px 0 24px;font-weight:600}p{color:#9fb2ac;line-height:1.7} .lede{font-size:22px;max-width:670px}h2{font-size:30px;letter-spacing:-.8px;margin:64px 0 22px}video{display:block;width:100%;border-radius:18px;background:#000;border:1px solid #263932}.video-grid{display:grid;grid-template-columns:3fr 1fr;gap:28px}.chapters{display:flex;flex-direction:column;gap:6px}.chapter{background:transparent;border:0;color:#b7c6c0;text-align:left;padding:10px;border-radius:8px;font:14px inherit;cursor:pointer}.chapter:hover{background:#17362d;color:white}.chapter span{display:inline-block;width:42px;color:#a2d9c7;font-variant-numeric:tabular-nums}.actions{display:flex;gap:25px;flex-wrap:wrap;margin:22px 0}a{color:#a2d9c7;text-underline-offset:5px}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:25px 0}.filters button{background:#14221e;border:1px solid #2c4037;border-radius:30px;padding:10px 19px;color:#afbeb8;font:inherit;cursor:pointer}.filters button[aria-pressed=true]{background:#a2d9c7;color:#0b2219;border-color:#a2d9c7}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}article{border:1px solid #24332d;border-radius:16px;overflow:hidden;background:#0e1915}.preview{display:block;height:240px;background:#071012}.preview img{width:100%;height:100%;object-fit:contain}.info{padding:23px}.info small{text-transform:uppercase;letter-spacing:2px;font-size:10px;color:#81bba6}.info h3{font-size:21px;font-weight:550;margin:12px 0}.info p{font-size:14px;min-height:48px}.download{font-size:13px}.note{border-top:1px solid #293e33;margin-top:60px;padding-top:25px;font-size:13px;max-width:950px}[hidden]{display:none!important}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}.video-grid{grid-template-columns:1fr}.chapters{display:grid;grid-template-columns:1fr 1fr}}@media(max-width:600px){main{padding:30px 20px}.grid{grid-template-columns:1fr}h1{margin-top:48px}.chapters{display:block}.preview{height:230px}}
</style><main><header><b>◴ &nbsp; Blocks</b><a href="README.md">Capture notes ↗</a></header><h1>One thing at a time.<br>Beautifully.</h1><p class="lede">A library of real native interactions, thoughtful defaults, and the small moments that make focused work feel good.</p><h2>The walkthrough</h2><div class="video-grid"><video controls preload="metadata" poster="screenshots/01-macbook-notch.png"><source src="video/blocks-walkthrough.mp4" type="video/mp4"><track kind="captions" src="video/blocks-walkthrough.vtt" srclang="en" label="English"></video><div class="chapters">CHAPTERS</div></div><div class="actions"><a download href="video/blocks-walkthrough.mp4">Download film · with music</a><a download href="video/blocks-walkthrough-silent.mp4">Silent version</a><a download href="video/blocks-walkthrough.srt">Subtitles</a></div><h2>The screenshot library <span style="color:#6e8d7e;font-size:18px">/ 15 images</span></h2><p>Device scenes, the complete task handoff, and daily, weekly, and project reports. Open an image at full size or download it directly.</p><nav class="filters" aria-label="Filter screenshots"><button aria-pressed="true" data-filter="All">All</button><button aria-pressed="false" data-filter="Devices">Devices</button><button aria-pressed="false" data-filter="Workflow">Workflow</button><button aria-pressed="false" data-filter="Reports">Reports</button></nav><div class="grid">CARDS</div><p class="note">Captured from native Blocks views with isolated sample data. Device hardware and wallpaper are illustrative; the walkthrough records real actions in a native capture harness. 64.9 seconds · 1920 × 1200 · 30 fps. <a href="README.md">Production notes</a> · <a href="contact-sheet.jpg">Contact sheet</a> · <a href="manifest.json">Asset manifest</a></p></main><script>document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('article').forEach(x=>x.hidden=b.dataset.filter!=='All'&&x.dataset.category!==b.dataset.filter)}));document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{const v=document.querySelector('video');v.currentTime=Number(b.dataset.time);v.play()}));</script></html>'''
(root/'index.html').write_text(page.replace('CARDS',''.join(cards)).replace('CHAPTERS',links))
srt=(root/'video/blocks-walkthrough.srt').read_text()
(root/'video/blocks-walkthrough.vtt').write_text('WEBVTT\n\n'+srt.replace(',', '.'))
print(f'Built gallery with {len(items)} verified image files')
